# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='موضوع خبر')),
                ('url_title', models.CharField(max_length=500, unique=True, verbose_name='موضوع خبر در url')),
                ('text1', models.TextField(verbose_name='متن خبر')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('text3', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('text4', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('text5', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('text6', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('text7', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('text8', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('date', models.CharField(max_length=100, verbose_name='تاریخ')),
                ('image_on_news_list_page', models.ImageField(upload_to='news', verbose_name='تصویر در لیست خبر ها')),
                ('image_on_news_detail_page', models.ImageField(upload_to='news', verbose_name='تصویر در جزییات خبر')),
                ('show_on_index_page', models.BooleanField(default=False, verbose_name='نشان دادن در صفحه ی اصلی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
