from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_index, name='admin-panel'),
    path('courses-users-list/<id>', views.admin_panel_course_users_detail_list, name='admin-panel-courses-users-list'),
    path('contacts/<int:id>', views.AnswerContactsView.as_view(), name='admin-panel-contacts'),
    path('courses/<search>/<page>', views.AdminPanelCoursesListView.as_view(), name='admin-panel-courses-list'),
    path('new-course/', views.AdminPanelCreateNewCourse.as_view(), name='admin-panel-create-new-course'),
    path('edit-course/<pk>', views.AdminPanelCourseChangeView.as_view(), name='admin-panel-change-course'),
    path('delete-course/<pk>', views.DeleteCourse.as_view(), name='admin-panel-delete-course'),
    path('course-prerequisites/<search>/<page>', views.AdminPanelPrerequisiteListView.as_view(),
         name='admin-panel-prerequisites-list'),
    path('delete-prerequisit-course/<pk>', views.DeletePrerequisiteView.as_view(),
         name='admin-panel-delete-prerequisite'),
    path('edit-prerequisit/<pk>', views.AdminPanelPrerequisiteChangeView.as_view(),
         name='admin-panel-change-prerequisite-course'),
    path('new-prerequisite/', views.AdminPanelCreateNewPrerequisite.as_view(),
         name='admin-panel-create-new-prerequisite'),
    path('course-categories/<search>/<page>', views.AdminPanelCategoryCourseListView.as_view(),
         name='admin-panel-categories-course-list'),
    path('delete-course-category/<pk>', views.DeleteCourseCategoryView.as_view(),
         name='admin-panel-delete-course-category'),
    path('edit-course-category/<pk>', views.AdminPanelCourseCategoryChangeView.as_view(),
         name='admin-panel-change-course-category-course'),
    path('new-course-category/', views.AdminPanelCreateNewCourseCategory.as_view(),
         name='admin-panel-create-new-course-category'),
    path('association/<search>/<page>', views.AdminPanelAssociationListView.as_view(),
         name='admin-panel-association-list'),
    path('edit-association/<pk>', views.AdminPanelAssociationChangeView.as_view(),
         name='admin-panel-change-association'),
    path('new-association/', views.AdminPanelCreateNewAssociation.as_view(),
         name='admin-panel-create-new-association'),
    path('delete-association/<pk>', views.DeleteAssociation.as_view(),
         name='admin-panel-delete-association'),
    path('association-goals/<search>/<page>', views.AdminPanelAssociationGoalsListView.as_view(),
         name='admin-panel-association-goals-list'),
    path('edit-association-goals/<pk>', views.AdminPanelAssociationGoalsChangeView.as_view(),
         name='admin-panel-change-association-goals'),
    path('new-association-goal/', views.AdminPanelCreateNewAssociationGoals.as_view(),
         name='admin-panel-create-new-association-goals'),
    path('delete-association-goal/<pk>', views.DeleteAssociationGoals.as_view(),
         name='admin-panel-delete-association-goal'),
    path('association-categories/<search>/<page>', views.AdminPanelAssociationCategoryListView.as_view(),
         name='admin-panel-association-categories-list'),
    path('edit-association-categories/<pk>', views.AdminPanelAssociationCategoryChangeView.as_view(),
         name='admin-panel-change-association-categories'),
    path('new-association-categories/', views.AdminPanelCreateNewAssociationCategory.as_view(),
         name='admin-panel-create-new-association-categories'),
    path('delete-association-categories/<pk>', views.DeleteAssociationCategory.as_view(),
         name='admin-panel-delete-association-categories'),
    path('science/<search>/<page>', views.AdminPanelScienceListView.as_view(), name='admin-panel-science-list'),
    path('edit-science/<pk>', views.AdminPanelScienceChangeView.as_view(), name='admin-panel-change-science'),
    path('new-science/', views.AdminPanelCreateNewScience.as_view(), name='admin-panel-create-new-science'),
    path('delete-science/<pk>', views.DeleteScience.as_view(), name='admin-panel-delete-science'),
    path('news/<search>/<page>', views.AdminPanelNewsListView.as_view(), name='admin-panel-news-list'),
    path('edit-news/<pk>', views.AdminPanelNewsChangeView.as_view(), name='admin-panel-change-news'),
    path('new-news/', views.AdminPanelCreateNewNews.as_view(), name='admin-panel-create-new-news'),
    path('delete-news/<pk>', views.DeleteNews.as_view(), name='admin-panel-delete-news'),
    path('user/<search>/<page>', views.AdminPanelUserListView.as_view(), name='admin-panel-user-list'),
    path('main-setting/<search>/<page>', views.AdminPanelMainSettingListView.as_view(),
         name='admin-panel-main-setting-list'),
    path('edit-main-setting/<pk>', views.AdminPanelMainSettingChangeView.as_view(),
         name='admin-panel-change-main-setting'),
    path('new-main-setting/', views.AdminPanelCreateNewMainSetting.as_view(),
         name='admin-panel-create-new-main-setting'),
    path('delete-main-setting/<pk>', views.DeleteMainSetting.as_view(),
         name='admin-panel-delete-main-setting'),
    path('about-us/<search>/<page>', views.AdminPanelAboutUsListView.as_view(),
         name='admin-panel-about-us-list'),
    path('edit-about-us/<pk>', views.AdminPanelAboutUsChangeView.as_view(),
         name='admin-panel-change-about-us'),
    path('new-about-us/', views.AdminPanelCreateNewAboutUs.as_view(),
         name='admin-panel-create-new-about-us'),
    path('delete-about-us/<pk>', views.DeleteAboutUs.as_view(),
         name='admin-panel-delete-about-us'),
    path('footer-category/<search>/<page>', views.AdminPanelFooterCategoryListView.as_view(),
         name='admin-panel-footer-category-list'),
    path('edit-footer-category/<pk>', views.AdminPanelFooterCategoryChangeView.as_view(),
         name='admin-panel-change-footer-category'),
    path('new-footer-category/', views.AdminPanelCreateNewFooterCategory.as_view(),
         name='admin-panel-create-new-footer-category'),
    path('delete-footer-category/<pk>', views.DeleteFooterCategory.as_view(),
         name='admin-panel-delete-footer-category'),
    path('footer-sub-category/<search>/<page>', views.AdminPanelFooterSubCategoryListView.as_view(),
         name='admin-panel-footer-sub-category-list'),
    path('edit-footer-sub-category/<pk>', views.AdminPanelFooterSubCategoryChangeView.as_view(),
         name='admin-panel-change-footer-sub-category'),
    path('new-footer-sub-category/', views.AdminPanelCreateNewFooterSubCategory.as_view(),
         name='admin-panel-create-new-footer-sub-category'),
    path('delete-footer-sub-category/<pk>', views.DeleteFooterSubCategory.as_view(),
         name='admin-panel-delete-footer-sub-category'),
                ]
