# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=200, verbose_name='نام کاربری دبیر')),
                ('sender', models.CharField(choices=[('teacher', 'دبیر'), ('user', 'کابر')], max_length=200, verbose_name='فرستنده')),
                ('text', models.TextField(verbose_name='متن')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'چت',
                'verbose_name_plural': 'چت ها',
            },
        ),
    ]
