# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=300, null=True, verbose_name='هدف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'هدف انجمن',
                'verbose_name_plural': 'اهداف انجمن',
            },
        ),
        migrations.CreateModel(
            name='AssociationsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='دسته بندی')),
                ('category_url', models.CharField(max_length=100, unique=True, verbose_name='دسته بندی در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='AssociationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=60, verbose_name='نام انجمن')),
                ('association_short_information', models.TextField(verbose_name='توضیحات کوتاه انجمن')),
                ('association_image_for_detail_page', models.ImageField(upload_to='associations', verbose_name='تصویر در صفحه ی جزییات')),
                ('association_image', models.ImageField(upload_to='associations', verbose_name='تصویر در صفحه ی لیست انجمن ها')),
                ('members_count', models.IntegerField(default=0, null=True, verbose_name='تعداد اعضای انجمن')),
                ('association_time', models.CharField(max_length=200, verbose_name='زمان برگزاری انجمن')),
                ('association_full_information', models.TextField(verbose_name='توضیحات کامل انجمن')),
                ('situation', models.CharField(max_length=200, null=True, verbose_name='وضعیت انجمن')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='لینک توییتر')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک')),
                ('show_on_main_page', models.BooleanField(default=False, verbose_name='نشان دادن در صفحه ی اصلی')),
                ('is_active', models.BooleanField(verbose_name='فعال / غبر فعال')),
                ('association_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.associationscategories', verbose_name='دسته بندی انجمن')),
            ],
            options={
                'verbose_name': 'انجمن',
                'verbose_name_plural': 'انجمن ها',
            },
        ),
    ]
