# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_module', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300, null=True)),
                ('thing', models.CharField(max_length=400, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('contact', 'contact'), ('change_course', 'change_course'), ('new_course', 'new_course'), ('delete_course', 'delete_course'), ('change_prerequisite', 'change_prerequisite'), ('new_prerequisite', 'new_prerequisite'), ('delete_prerequisite', 'delete_prerequisite'), ('change_course_category', 'change_course_category'), ('new_course_category', 'new_course_category'), ('delete_course_category', 'delete_course_category'), ('new_association', 'new_association'), ('change_association', 'change_association'), ('delete_association', 'delete_association'), ('new_association_goal', 'new_association_goal'), ('change_association_goal', 'change_association_goal'), ('delete_association_goal', 'delete_association_goal'), ('new_association_category', 'new_association_category'), ('change_association_category', 'change_association_category'), ('delete_association_category', 'delete_association_category'), ('new_science', 'new_science'), ('change_science', 'change_science'), ('delete_science', 'delete_science'), ('new_news', 'new_news'), ('change_news', 'change_news'), ('delete_news', 'delete_news'), ('new_user', 'new_user'), ('change_user', 'change_user'), ('change_main_setting', 'change_main_setting'), ('delete_main_setting', 'delete_main_setting'), ('new_main_setting', 'new_main_setting'), ('change_about_us', 'change_about_us'), ('delete_about_us', 'delete_about_us'), ('new_about_us', 'new_about_us'), ('change_footer_category', 'change_footer_category'), ('delete_footer_category', 'delete_footer_category'), ('new_footer_category', 'new_footer_category'), ('change_footer_sub_category', 'change_footer_sub_category'), ('delete_footer_sub_category', 'delete_footer_sub_category'), ('new_footer_sub_category', 'new_footer_sub_category')], max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPanelShowCoursesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_counts', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_module.coursesmodel')),
            ],
        ),
    ]
