# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام تنظیمات')),
                ('main_text', models.TextField(verbose_name='متن اصلی ')),
                ('second_text', models.TextField(verbose_name='متن دوم')),
                ('address', models.CharField(max_length=200, verbose_name='ادرس')),
                ('phone_number', models.CharField(max_length=20, verbose_name='تلفن')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'درباره ی ما',
                'verbose_name_plural': 'درباره ی ما',
            },
        ),
    ]
