# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='پیام')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('dose_answered', models.BooleanField(default=False, verbose_name='جواب داده شده / نشده')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
