# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBoxCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('url', models.CharField(max_length=500, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'دسته یندی فوتر',
                'verbose_name_plural': 'دسته بندی ها ی فوتر',
            },
        ),
        migrations.CreateModel(
            name='SiteSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_setting_name', models.CharField(max_length=50, verbose_name='نام تنظیمات')),
                ('site_logo_1', models.ImageField(upload_to='site-logo', verbose_name='لوگو ی سایت')),
                ('site_logo_2', models.ImageField(null=True, upload_to='site-logo', verbose_name='لوگو ی سایت')),
                ('h1_text_main_page', models.CharField(max_length=70, verbose_name='عنوان سایز h1 در بالا ی صفحه ی اصلی')),
                ('under_h1_text', models.TextField(verbose_name='متن زیر عنوان h1')),
                ('any_button', models.BooleanField(verbose_name='دکمه ی زیر متن فعال / غیر فعال')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='نوشته ی دکمه')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='لینک دکمه')),
                ('decoration', models.CharField(choices=[('white', 'روشن'), ('dark', 'تیره'), ('white_or_dark', 'انتخواب کاربر')], max_length=100, null=True, verbose_name='دکوریشن')),
                ('footer_text', models.TextField(verbose_name='متن فوتر')),
                ('instagram_link', models.URLField(verbose_name='لینک اینستاگرام')),
                ('twitter_link', models.URLField(verbose_name='لینک توییتر')),
                ('facebook_link', models.URLField(verbose_name='لینک فیس بوک')),
                ('footer_phone_number', models.CharField(max_length=15, verbose_name='شماره تماس در فوتر')),
                ('is_active', models.BooleanField(null=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='FooterBoxSubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link', models.URLField(max_length=500, verbose_name='لینک')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesetting_module.footerboxcategorymodel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
    ]
