# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='دسته بندی دوره')),
                ('category_url', models.CharField(max_length=500, verbose_name='دسته بندی در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی دوره',
                'verbose_name_plural': 'دسته بندی های دوره',
            },
        ),
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام دوره')),
                ('price', models.CharField(max_length=200, verbose_name='قیمت دوره')),
                ('situation', models.CharField(max_length=200, verbose_name='وضعیت')),
                ('image_on_courses_list', models.ImageField(upload_to='courses', verbose_name='تصویر دوره در صفحه ی دوره ها')),
                ('image_on_course_detail', models.ImageField(upload_to='courses', verbose_name='تصویر دوره در صفحه ی جزییات دوره')),
                ('short_information', models.TextField(verbose_name='توضیحات کوتاه')),
                ('full_information', models.TextField(verbose_name='توضیحات کامل')),
                ('time', models.CharField(max_length=200, verbose_name='زمان دوره')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
                ('register_time', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='ProfitCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.CharField(max_length=500, verbose_name='پیش نیاز')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_module.coursesmodel', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'پیش نیاز',
                'verbose_name_plural': 'پیش نیاز ها',
            },
        ),
        migrations.CreateModel(
            name='OwnedCoursesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, null=True, to='course_module.coursesmodel', verbose_name='دوره ها')),
            ],
            options={
                'verbose_name': 'دوره ی خریداری شده',
                'verbose_name_plural': 'دوره های خریداری شده',
            },
        ),
    ]
