# Generated by Django 4.2.3 on 2023-07-13 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedcoursesuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_module.coursescategory', verbose_name='دسته بندی دوره'),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دبیر دوره'),
        ),
    ]
